- name: Upgrade all packages
  ansible.builtin.apt:
    name: '*'
    state: latest

- name: "Install nodejs, npm and pm2"
  ansible.builtin.apt:
    name: "{{packages}}"
    vars:
      packages:
        - npm
        - nodejs
        - pm2